name: Gen AI CI
on:
  workflow_dispatch:
  push:
    branches: [ manualTrigger ]
  pull_request:
    branches: [ manualTrigger ]
defaults:
  run:
    working-directory: ./Pokedex

env:
  SONAR_TOKEN: '75621cba6337eff300a0b42e8d68eb9d4cdbe709'
  SONAR_HOST_URL: 'http://brillioonesonar.eastus.cloudapp.azure.com:9000'
  sonar.projectKey: 'GenAISonarQubeTesting'
  sonar.projectName: 'GenAISonarQubeTesting'

jobs:
  build:
    runs-on: 
      - self-hosted
      - label-1
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Test
      run: dotnet test --no-build --verbosity normal --settings coverlet.runsettings
      
    - name: Publish Artifacts
      uses: azure/CLI@v1
      with:
        azcliversion: latest
        inlineScript: |
          az storage blob upload-batch --destination github-artifacts --source ./ --connection-string "${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}"
      
    - name: SonarQube Scan
      uses: SonarSource/sonarqube-scan-action@v1.2.0
      with:
        SONAR_TOKEN: ${{env.SONAR_TOKEN }}
        projectKey: ${{ env.sonar.projectKey }}
        projectName: ${{ env.sonar.projectName }}
        SONAR_HOST_URL: ${{ env.SONAR_HOST_URL }}
      
      
    
